### ISSUE TITLE
Add Order Line Items table and order summary table to DB

### ISSUE THREAD

**Issue by StevenBallardSB** [zjmichaels/notableWholesale_Spring#6]
The fields for the order line items table is as follows
- OrderId Foreign Key
- Product Id Foreign Key
- Quantity Integer required

The fields for the order summary table is as follows
- OrderId Primary Key
- UserId Foreign Key
- Price int required
- Status varchar required

**Comment by rsithideth** [comment]
Finished creating script for both tables
